//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Utility;

    public partial class db_Zon_HuwEntities : DbContext
    {
        public db_Zon_HuwEntities()
            : base("name=db_Zon_HuwEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AddressType> AddressTypes { get; set; }
        public DbSet<BusinessType> BusinessTypes { get; set; }
        public DbSet<Cashback_Coupons> Cashback_Coupons { get; set; }
        public DbSet<Cashback_Coups_Transactions> Cashback_Coups_Transactions { get; set; }
        public DbSet<CashBackTable> CashBackTables { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CBC_Data_Tree> CBC_Data_Tree { get; set; }
        public DbSet<CheckOutPaymentTransaction> CheckOutPaymentTransactions { get; set; }
        public DbSet<CheckOutUserProductTransaction> CheckOutUserProductTransactions { get; set; }
        public DbSet<Configuration> Configurations { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<def_accesss> def_accesss { get; set; }
        public DbSet<Deff_GST> Deff_GST { get; set; }
        public DbSet<Delivery_Invoice_Excel> Delivery_Invoice_Excel { get; set; }
        public DbSet<Delivery_Invoice_Excel_Upload_Details> Delivery_Invoice_Excel_Upload_Details { get; set; }
        public DbSet<Delivery_Invoice_Pdf> Delivery_Invoice_Pdf { get; set; }
        public DbSet<FeaturesCategory> FeaturesCategories { get; set; }
        public DbSet<FeaturesSubCategory> FeaturesSubCategories { get; set; }
        public DbSet<Medicines_tbl> Medicines_tbl { get; set; }
        public DbSet<NoftifyMe> NoftifyMes { get; set; }
        public DbSet<OfflineSale> OfflineSales { get; set; }
        public DbSet<PaymentTransaction> PaymentTransactions { get; set; }
        public DbSet<PendingCashBackTable> PendingCashBackTables { get; set; }
        public DbSet<PinCodesInformation> PinCodesInformations { get; set; }
        public DbSet<Prescription_Upload_tbl> Prescription_Upload_tbl { get; set; }
        public DbSet<Processed_By_Info> Processed_By_Info { get; set; }
        public DbSet<ProductFeature> ProductFeatures { get; set; }
        public DbSet<ProductInventory> ProductInventories { get; set; }
        public DbSet<ProductReview> ProductReviews { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductsGallery> ProductsGalleries { get; set; }
        public DbSet<ProductSpecification> ProductSpecifications { get; set; }
        public DbSet<RelatedProduct> RelatedProducts { get; set; }
        public DbSet<Remitting_Excel_Data> Remitting_Excel_Data { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Routine_Customers_Table> Routine_Customers_Table { get; set; }
        public DbSet<SpecificationType> SpecificationTypes { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Stored_Temp_File> Stored_Temp_File { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<SubProduct> SubProducts { get; set; }
        public DbSet<SuperCategory> SuperCategories { get; set; }
        public DbSet<TaxesConfiguration> TaxesConfigurations { get; set; }
        public DbSet<tbl_accesspages> tbl_accesspages { get; set; }
        public DbSet<Tbl_AdditionalInfo> Tbl_AdditionalInfo { get; set; }
        public DbSet<Tbl_CheckoutOrderComments> Tbl_CheckoutOrderComments { get; set; }
        public DbSet<Tbl_Coupon_Info> Tbl_Coupon_Info { get; set; }
        public DbSet<Tbl_Covid> Tbl_Covid { get; set; }
        public DbSet<Tbl_Diagnostictests> Tbl_Diagnostictests { get; set; }
        public DbSet<Tbl_InpackingBox_Details> Tbl_InpackingBox_Details { get; set; }
        public DbSet<tbl_Loghistory> tbl_Loghistory { get; set; }
        public DbSet<Tbl_Outofstock> Tbl_Outofstock { get; set; }
        public DbSet<Tbl_Packing_Box> Tbl_Packing_Box { get; set; }
        public DbSet<Tbl_Prescriptionorders> Tbl_Prescriptionorders { get; set; }
        public DbSet<Tbl_Presecription_Info> Tbl_Presecription_Info { get; set; }
        public DbSet<Temp_Deliver_Excel_Record> Temp_Deliver_Excel_Record { get; set; }
        public DbSet<UserAddress> UserAddresses { get; set; }
        public DbSet<UserProductTransaction> UserProductTransactions { get; set; }
        public DbSet<UserProductTransactionSpecification> UserProductTransactionSpecifications { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<dbo_Newsletter> dbo_Newsletter { get; set; }
        public DbSet<Tbl_Action> Tbl_Action { get; set; }
        public DbSet<Tbl_AWB> Tbl_AWB { get; set; }
        public DbSet<Tbl_Need_Help> Tbl_Need_Help { get; set; }
        public DbSet<Tbl_Need_Help_Comments> Tbl_Need_Help_Comments { get; set; }
        public DbSet<Tbl_Offered_Products> Tbl_Offered_Products { get; set; }
        public DbSet<Tbl_OrderComments> Tbl_OrderComments { get; set; }
        public DbSet<Tbl_Promo_Codes> Tbl_Promo_Codes { get; set; }
        public DbSet<Page1> Page1 { get; set; }
        public DbSet<PincodeInfo> PincodeInfoes { get; set; }
        public DbSet<RetunOrder> RetunOrders { get; set; }
        public DbSet<Temp_File_Data> Temp_File_Data { get; set; }
    }
}
