//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessType
    {
        public BusinessType()
        {
            this.FeaturesCategories = new HashSet<FeaturesCategory>();
        }
    
        public int BusinessId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessDescription { get; set; }
    
        public virtual ICollection<FeaturesCategory> FeaturesCategories { get; set; }
    }
}
