//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashback_Coupons
    {
        public long Coup_ID { get; set; }
        public Nullable<long> Defaultid { get; set; }
        public string Coup_Code { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<decimal> Coup_Percentage { get; set; }
        public Nullable<decimal> Coup_Amount { get; set; }
        public Nullable<int> Total_Times_Usable { get; set; }
        public Nullable<int> Total_Times_Usable_Per_User { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Min_Qty { get; set; }
        public Nullable<bool> New_User { get; set; }
        public Nullable<int> Min_Prod_Val { get; set; }
        public Nullable<decimal> Max_Cashback { get; set; }
        public string Cashbackdesc { get; set; }
        public string TC { get; set; }
    }
}
