//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBackTable
    {
        public long CashbackID { get; set; }
        public string orderid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string totalAmount { get; set; }
        public string credit { get; set; }
        public string debit { get; set; }
        public string balance { get; set; }
        public string Userid { get; set; }
        public string PGTxnid { get; set; }
        public string Messages { get; set; }
    }
}
