//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashback_Coups_Transactions
    {
        public long CCPT_ID { get; set; }
        public Nullable<long> Coup_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<long> Cashback_Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> orderID { get; set; }
    }
}
