//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBC_Data_Tree
    {
        public long CBC_ID { get; set; }
        public Nullable<long> Prod_ID { get; set; }
        public Nullable<long> Coup_ID { get; set; }
        public Nullable<long> Defaultid { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
    }
}
