//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOutPaymentTransaction
    {
        public CheckOutPaymentTransaction()
        {
            this.CheckOutUserProductTransactions = new HashSet<CheckOutUserProductTransaction>();
            this.Tbl_CheckoutOrderComments = new HashSet<Tbl_CheckoutOrderComments>();
        }
    
        public long PaymentTransactionId { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string TxnRefNo { get; set; }
        public string PGTxnId { get; set; }
        public string TxnStatus { get; set; }
        public string TxnMessage { get; set; }
        public Nullable<decimal> TxnAmount { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> ShippingCharges { get; set; }
        public int PaymentStatus { get; set; }
        public string CurrencyCode { get; set; }
        public decimal CurrencyValue { get; set; }
        public string CurrencySymbol { get; set; }
        public string ShipmentId { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string ShipmentType { get; set; }
        public string ShipmentURL { get; set; }
        public string Location { get; set; }
        public Nullable<long> Free_Product_ID { get; set; }
        public bool Authorized { get; set; }
        public bool Pickup { get; set; }
        public string PickupID { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public bool Dispatched { get; set; }
        public string DispatchedID { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
        public bool Delivered { get; set; }
        public string DeliveredID { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public string CourierName { get; set; }
        public int OrderCurrentStatus { get; set; }
        public string ReceivedBy { get; set; }
        public string Comments { get; set; }
        public string OrdersReturnReason { get; set; }
        public string OrdersReturnAction { get; set; }
        public bool AmountFromMyAccount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<bool> Has_Promo_Code { get; set; }
        public Nullable<int> Promo_Code_ID { get; set; }
        public Nullable<decimal> Promo_Code_Amount { get; set; }
        public Nullable<int> Offer_Product_ID { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Tbl_Promo_Codes Tbl_Promo_Codes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CheckOutUserProductTransaction> CheckOutUserProductTransactions { get; set; }
        public virtual ICollection<Tbl_CheckoutOrderComments> Tbl_CheckoutOrderComments { get; set; }
    }
}
