//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Invoice_Excel
    {
        public int Id { get; set; }
        public string Order_id { get; set; }
        public string waybill_no { get; set; }
        public string package_type { get; set; }
        public string status { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<int> D_Pin { get; set; }
        public Nullable<int> R_Pin { get; set; }
        public string Item_Shipped { get; set; }
        public Nullable<int> Document_Id { get; set; }
    }
}
