//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Invoice_Pdf
    {
        public int Id { get; set; }
        public string Pdf_Name { get; set; }
        public string Pdf_Date { get; set; }
    }
}
