//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturesSubCategory
    {
        public FeaturesSubCategory()
        {
            this.ProductFeatures = new HashSet<ProductFeature>();
        }
    
        public int FeaturesSubCategoryId { get; set; }
        public int FeaturesCategoryId { get; set; }
        public string FeaturesSubCategoryName { get; set; }
    
        public virtual FeaturesCategory FeaturesCategory { get; set; }
        public virtual ICollection<ProductFeature> ProductFeatures { get; set; }
    }
}
