//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturesCategory
    {
        public FeaturesCategory()
        {
            this.FeaturesSubCategories = new HashSet<FeaturesSubCategory>();
        }
    
        public int FeaturesCategoryId { get; set; }
        public int BusinessId { get; set; }
        public string FeaturesCategoryName { get; set; }
    
        public virtual BusinessType BusinessType { get; set; }
        public virtual ICollection<FeaturesSubCategory> FeaturesSubCategories { get; set; }
    }
}
