//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines_tbl
    {
        public long Med_Id { get; set; }
        public string ItemID { get; set; }
        public string company { get; set; }
        public string Item_Code { get; set; }
        public string Med_Name { get; set; }
        public string HSNCode { get; set; }
        public string LocalTax { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> stock { get; set; }
    }
}
