//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoftifyMe
    {
        public long RequestId { get; set; }
        public long ProductId { get; set; }
        public string UserName { get; set; }
        public string EmailId { get; set; }
        public decimal MobileNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpDatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
