//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinCodesInformation
    {
        public long PinCodeId { get; set; }
        public string ControlingStation { get; set; }
        public string LocationCode { get; set; }
        public string DefaultCity { get; set; }
        public string Pincode { get; set; }
        public string District { get; set; }
        public string State_UnionTerritory { get; set; }
        public string Zone { get; set; }
        public string Region { get; set; }
        public string EXP { get; set; }
        public string CGO { get; set; }
        public string SFC { get; set; }
        public string ToPay { get; set; }
        public string COD { get; set; }
        public string StationType { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public decimal ShippingAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
