//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Upload_tbl
    {
        public long Prescription_ID { get; set; }
        public long transaction_ID { get; set; }
        public long User_ID { get; set; }
        public int Prescription_Type { get; set; }
        public Nullable<int> Only_Duration { get; set; }
        public string Own_selection_Medicines { get; set; }
        public Nullable<int> Own_selection_Duration { get; set; }
        public Nullable<bool> Call_Me { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
