//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processed_By_Info
    {
        public long Processed_By_Id { get; set; }
        public long Order_Id { get; set; }
        public long Employee_Id { get; set; }
        public System.DateTime Created_On { get; set; }
        public string comments { get; set; }
    }
}
