//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public long ReviewId { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Review { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
