//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventory
    {
        public long ProductQtyInventoryId { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> SubProductId { get; set; }
        public int ProductQuantity { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SubProduct SubProduct { get; set; }
    }
}
