//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CheckOutUserProductTransactions = new HashSet<CheckOutUserProductTransaction>();
            this.NoftifyMes = new HashSet<NoftifyMe>();
            this.ProductFeatures = new HashSet<ProductFeature>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.ProductReviews = new HashSet<ProductReview>();
            this.ProductsGalleries = new HashSet<ProductsGallery>();
            this.ProductSpecifications = new HashSet<ProductSpecification>();
            this.RelatedProducts = new HashSet<RelatedProduct>();
            this.RelatedProducts1 = new HashSet<RelatedProduct>();
            this.SubProducts = new HashSet<SubProduct>();
            this.UserProductTransactions = new HashSet<UserProductTransaction>();
        }
    
        public long ProductId { get; set; }
        public string ProductCode { get; set; }
        public long SubCategoryId { get; set; }
        public bool IsFeaturedProduct { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int Quantity { get; set; }
        public string ProductColor { get; set; }
        public string Occasion { get; set; }
        public decimal ProductOriginalCost { get; set; }
        public decimal ProductCost { get; set; }
        public decimal ProductDiscountPercentage { get; set; }
        public decimal ProductDiscountCost { get; set; }
        public string ProductImgUrl { get; set; }
        public string ProductImgUrl2 { get; set; }
        public string ProductFeaturesContent { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsSold { get; set; }
        public bool CanCompare { get; set; }
        public bool HasReviews { get; set; }
        public bool CanReviewsNeedPermission { get; set; }
        public string Brand { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<int> SoldQty { get; set; }
        public string SizeGuidePath { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<long> Free_Product_ID { get; set; }
        public Nullable<bool> Is_Free_Product_Active { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Keywords { get; set; }
        public string Page_Title { get; set; }
        public Nullable<bool> IsPresciption { get; set; }
        public Nullable<int> Weight { get; set; }
        public string H2Tag { get; set; }
        public Nullable<decimal> GST { get; set; }
        public string BatchNo { get; set; }
        public string HSNCode { get; set; }
        public string CdnProductImgUrl { get; set; }
        public string CdnProductImgUrl2 { get; set; }

        public virtual ICollection<CheckOutUserProductTransaction> CheckOutUserProductTransactions { get; set; }
        public virtual ICollection<NoftifyMe> NoftifyMes { get; set; }
        public virtual ICollection<ProductFeature> ProductFeatures { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<ProductsGallery> ProductsGalleries { get; set; }
        public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; }
        public virtual ICollection<RelatedProduct> RelatedProducts { get; set; }
        public virtual ICollection<RelatedProduct> RelatedProducts1 { get; set; }
        public virtual ICollection<SubProduct> SubProducts { get; set; }
        public virtual ICollection<UserProductTransaction> UserProductTransactions { get; set; }
    }
}
