//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        public ProductSpecification()
        {
            this.UserProductTransactionSpecifications = new HashSet<UserProductTransactionSpecification>();
        }
    
        public long ProductSpecificationId { get; set; }
        public long ProductId { get; set; }
        public int SpecificationTypeId { get; set; }
        public string ProductSpecificationName { get; set; }
        public string ProductSpecificationNameValues { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SpecificationType SpecificationType { get; set; }
        public virtual ICollection<UserProductTransactionSpecification> UserProductTransactionSpecifications { get; set; }
    }
}
