//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remitting_Excel_Data
    {
        public long Remitting_ID { get; set; }
        public Nullable<long> AWB_number { get; set; }
        public Nullable<long> Order_Number { get; set; }
        public Nullable<System.DateTime> Pickup_Date { get; set; }
        public string Origin { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public Nullable<long> COD_Due { get; set; }
        public Nullable<long> Remitted_Amount { get; set; }
        public Nullable<long> Balance { get; set; }
        public string Dest_Centre { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Del_Date { get; set; }
        public string Payment_Ref_and_Date { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Ref { get; set; }
    }
}
