//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationType
    {
        public SpecificationType()
        {
            this.ProductSpecifications = new HashSet<ProductSpecification>();
        }
    
        public int SpecificationTypeId { get; set; }
        public string Specification { get; set; }
    
        public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; }
    }
}
