//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProduct
    {
        public SubProduct()
        {
            this.CheckOutUserProductTransactions = new HashSet<CheckOutUserProductTransaction>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.UserProductTransactions = new HashSet<UserProductTransaction>();
        }
    
        public long SubProductId { get; set; }
        public long ProductId { get; set; }
        public string SPName { get; set; }
        public decimal ProductOriginalCost { get; set; }
        public decimal ProductDiscountPercentage { get; set; }
        public decimal ProductDiscountCost { get; set; }
        public decimal ProductCost { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<CheckOutUserProductTransaction> CheckOutUserProductTransactions { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<UserProductTransaction> UserProductTransactions { get; set; }
    }
}
