//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Action
    {
        public long Action_ID { get; set; }
        public string Action_Performed { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public string Table_Name { get; set; }
        public Nullable<int> Action_Performed_By { get; set; }
        public System.DateTime Action_Performed_Date { get; set; }
        public Nullable<int> Read_By { get; set; }
        public Nullable<System.DateTime> Read_Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
