//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InpackingBox_Details
    {
        public int Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string Lengths { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string V_weight { get; set; }
        public string Actual_Weight { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
    }
}
