//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Need_Help
    {
        public long Help_Id { get; set; }
        public string Person_Name { get; set; }
        public string Person_Contact { get; set; }
        public string Person_Email_Id { get; set; }
        public Nullable<System.DateTime> Help_Date { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
