//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Prescriptionorders
    {
        public long OrderId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Orderitems { get; set; }
        public string PatientName { get; set; }
        public string Prescriptionurl { get; set; }
        public string Address { get; set; }
        public string Locality { get; set; }
        public string Pincode { get; set; }
        public string Deliverytype { get; set; }
        public Nullable<int> Status { get; set; }
        public string OrderplacedUrl { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string AdminComments { get; set; }
        public string UserComments { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BillNo { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string PaymentMode { get; set; }
        public string DeliveredBy { get; set; }
    }
}
