//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Diagnostictests
    {
        public long DiagnosticId { get; set; }
        public string DiagnosticCode { get; set; }
        public string DiagnosticName { get; set; }
        public string DiagnosticTests { get; set; }
        public string Price { get; set; }
        public string ActualPrice { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
