//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loghistory
    {
        public int ID { get; set; }
        public int OrdersStatusId { get; set; }
        public string OrderStatusname { get; set; }
        public string Createdby { get; set; }
        public System.DateTime Createdon { get; set; }
        public string ReferenceNO { get; set; }
        public Nullable<long> Paymenttransactionid { get; set; }
    }
}
