//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Coupon_Info
    {
        public long Coupon_Id { get; set; }
        public string Coupon_Code { get; set; }
        public Nullable<System.DateTime> Valid_From { get; set; }
        public Nullable<System.DateTime> Valid_To { get; set; }
        public Nullable<decimal> Min_Cart_Value { get; set; }
        public Nullable<decimal> Coupon_Percentage { get; set; }
        public Nullable<decimal> Coupon_Amount { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<long> Product_Id { get; set; }
        public Nullable<bool> Only_Particular_Users { get; set; }
        public Nullable<int> Total_No_Of_Times_Usage { get; set; }
        public Nullable<int> No_Of_Usages_Per_User { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
