//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Promo_Codes
    {
        public Tbl_Promo_Codes()
        {
            this.CheckOutPaymentTransactions = new HashSet<CheckOutPaymentTransaction>();
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
        }
    
        public int Promo_Code_ID { get; set; }
        public string PromoCode { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Valid_From { get; set; }
        public System.DateTime Valid_To { get; set; }
        public Nullable<decimal> Minimum_Order_amount { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CheckOutPaymentTransaction> CheckOutPaymentTransactions { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
    }
}
