//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Offered_Products
    {
        public int Offer_Product_ID { get; set; }
        public string Offer_Product_Name { get; set; }
        public Nullable<decimal> Product_Actual_Cost { get; set; }
        public Nullable<decimal> Offer_Cost { get; set; }
        public Nullable<System.DateTime> Offer_Valid_From { get; set; }
        public Nullable<System.DateTime> Offer_Valid_To { get; set; }
        public string Product_Brand { get; set; }
        public string Product_Image { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
