//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderComments
    {
        public long Comment_ID { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Order_Id { get; set; }
        public Nullable<System.DateTime> Comment_Date { get; set; }
        public Nullable<int> Commented_By { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual PaymentTransaction PaymentTransaction { get; set; }
    }
}
