//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Presecription_Info
    {
        public long Prescription_Id { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<long> Payment_Transaction_Id { get; set; }
        public string Prescription_Image { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
