//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AdditionalInfo
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public Nullable<System.DateTime> Manufacturer_Date { get; set; }
        public Nullable<int> Best_Before_Date { get; set; }
        public string Country_Of_Origin { get; set; }
        public string GTIN { get; set; }
        public string Manufacturer_Details { get; set; }
        public string Marketerdetails { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string BatchNo { get; set; }
    }
}
