//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AWB
    {
        public long AWB_ID { get; set; }
        public string AWB_Number { get; set; }
        public long OrderId { get; set; }
        public int PaymentMode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Deliverytype { get; set; }
    }
}
