//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Deliver_Excel_Record
    {
        public int Id { get; set; }
        public Nullable<long> Order_id { get; set; }
        public string Items_shipped { get; set; }
        public string Waybill_num { get; set; }
        public Nullable<System.DateTime> Pickup_date { get; set; }
        public string Package_type { get; set; }
        public Nullable<int> Product_value { get; set; }
        public string Status { get; set; }
        public string Zone { get; set; }
        public Nullable<decimal> Charged_weight { get; set; }
        public Nullable<decimal> Gross_amount { get; set; }
        public Nullable<decimal> charge_POD { get; set; }
        public Nullable<decimal> charge_COVID { get; set; }
        public Nullable<decimal> charge_FSC { get; set; }
        public Nullable<decimal> charge_DL { get; set; }
        public Nullable<decimal> charge_RTO { get; set; }
        public Nullable<decimal> charge_DTO { get; set; }
        public Nullable<decimal> charge_COD { get; set; }
        public Nullable<decimal> charge_FS { get; set; }
        public Nullable<decimal> charge_FOV { get; set; }
        public Nullable<decimal> charge_CCOD { get; set; }
        public Nullable<decimal> charge_WOD { get; set; }
        public Nullable<decimal> charge_AIR { get; set; }
        public Nullable<decimal> charge_pickup { get; set; }
        public Nullable<decimal> charge_DEMUR { get; set; }
        public Nullable<decimal> charge_LABEL { get; set; }
        public Nullable<decimal> charge_REATTEMPT { get; set; }
        public Nullable<decimal> charge_DOCUMENT { get; set; }
        public Nullable<decimal> charge_ROV { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST_UGST { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string destination_pin { get; set; }
        public string opin { get; set; }
        public string dpin { get; set; }
        public string rpin { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
