//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public UserAddress()
        {
            this.CheckOutUserProductTransactions = new HashSet<CheckOutUserProductTransaction>();
            this.CheckOutUserProductTransactions1 = new HashSet<CheckOutUserProductTransaction>();
            this.UserProductTransactions = new HashSet<UserProductTransaction>();
            this.UserProductTransactions1 = new HashSet<UserProductTransaction>();
        }
    
        public long UserAddressId { get; set; }
        public int AddressTypeId { get; set; }
        public long UserId { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public string City { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string LandMark { get; set; }
        public string PinCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpDatedOn { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<CheckOutUserProductTransaction> CheckOutUserProductTransactions { get; set; }
        public virtual ICollection<CheckOutUserProductTransaction> CheckOutUserProductTransactions1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<UserProductTransaction> UserProductTransactions { get; set; }
        public virtual ICollection<UserProductTransaction> UserProductTransactions1 { get; set; }
    }
}
