//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProductTransaction
    {
        public UserProductTransaction()
        {
            this.UserProductTransactionSpecifications = new HashSet<UserProductTransactionSpecification>();
        }
    public string CashbackAmount { get; set; }
        public long TransactionId { get; set; }
        public long PaymentTransactionId { get; set; }
        public long UserId { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> SubProductId { get; set; }
        public int Quantity { get; set; }
        public decimal ProductCost { get; set; }
        public decimal ProductDiscountPercentage { get; set; }
        public decimal ProductDiscountCost { get; set; }
        public long ShippingAddressId { get; set; }
        public long BillingAddressId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public int Status { get; set; }
        public string CurrencyCode { get; set; }
        public decimal CurrencyValue { get; set; }
        public string CurrencySymbol { get; set; }
        public string OrdersReturnReason { get; set; }
        public string OrdersReturnAction { get; set; }
        public long ReplacementTransactionId { get; set; }
        public bool IsReplaced { get; set; }
        public Nullable<bool> Isprescription { get; set; }
        public string CashBackAmount { get; set; }
        public Nullable<int> Weight { get; set; }
        public string ProductName { get; set; }
    
        public virtual PaymentTransaction PaymentTransaction { get; set; }
        public virtual Product Product { get; set; }
        public virtual SubProduct SubProduct { get; set; }
        public virtual UserAddress UserAddress { get; set; }
        public virtual UserAddress UserAddress1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserProductTransactionSpecification> UserProductTransactionSpecifications { get; set; }
    }
}
