//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProductTransactionSpecification
    {
        public long Id { get; set; }
        public long TransactionId { get; set; }
        public long ProductSpecificationId { get; set; }
        public string SpecificationValue { get; set; }
    
        public virtual ProductSpecification ProductSpecification { get; set; }
        public virtual UserProductTransaction UserProductTransaction { get; set; }
    }
}
