//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CheckOutPaymentTransactions = new HashSet<CheckOutPaymentTransaction>();
            this.CheckOutUserProductTransactions = new HashSet<CheckOutUserProductTransaction>();
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
            this.ProductReviews = new HashSet<ProductReview>();
            this.UserProductTransactions = new HashSet<UserProductTransaction>();
        }
    
        public long UserId { get; set; }
        public int RoleId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string PassCode { get; set; }
        public decimal MobileNo { get; set; }
        public Nullable<decimal> AlternateContactNumber { get; set; }
        public int RegStatus { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpDatedOn { get; set; }
        public Nullable<decimal> MyAccountBalance { get; set; }
    
        public virtual ICollection<CheckOutPaymentTransaction> CheckOutPaymentTransactions { get; set; }
        public virtual ICollection<CheckOutUserProductTransaction> CheckOutUserProductTransactions { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserProductTransaction> UserProductTransactions { get; set; }
    }
}
